laravel/routes/web.php
<?php

Auth::routes();


Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('notes', 'NoteController');
    Route::resource('users', 'UserController');

});

laravel/app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable = ['user_id', 'title', 'note'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

laravel/app/Http/Controllers/Api/NoteController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Note;
use Illuminate\Http\Request;

class NoteController extends Controller
{

    public function index(Request $request)
    {
        $id = $request->get("id");
        return Note::where('user_id', $id)->orderBy('id', 'desc')->get();
    }

    public function store(Request $request)
    {

//        $request->validate([
//            'user_id' => 'required',
//            'title' => 'required',
//            'note' => 'required',
//        ]);
//        return $request;

        $result = Note::create($request->all());
        return $result;
    }


    public function show(Note $note)
    {
        return $note;
    }


    public function update(Request $request, Note $note)
    {
        $request->validate([
            'user_id' => 'required',
            'title' => 'required',
            'note' => 'required',
        ]);
        $note->update($request->all());

        return $note;
    }


    public function destroy(Note $note)
    {
        $note->delete();
        return true;
    }

    public function delete(Request $request)
    {
        return $request;
//        $note->delete();
        return true;
    }
}

laravel/app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Note;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NoteController extends Controller
{

    public function index()
    {
        $id = auth()->user()->id;
        $notes = Note::where('user_id', $id)->latest()->paginate(10);

        return view('notes.index', compact('notes'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    public function create()
    {
        return view('notes.create');
    }

    public function store(Request $request)
    {


        $request->validate([
            'user_id' => 'required',
            'title' => 'required',
            'note' => 'required',
        ]);

        Note::create($request->all());

        return redirect()->route('notes.index')
            ->with('success', 'Note created successfully.');
    }

    public function show(Note $note)
    {
        return view('notes.show', compact('note'));
    }

    public function edit(Note $note)
    {
        return view('notes.edit', compact('note'));
    }

    public function update(Request $request, Note $note)
    {
        $request->validate([
            'user_id' => 'required',
            'title' => 'required',
            'note' => 'required',
        ]);

        $note->update($request->all());

        return redirect()->route('notes.index')
            ->with('success', 'Note updated successfully');
    }

    public function destroy(Note $note)
    {
        $note->delete();

        return redirect()->route('notes.index')
            ->with('success', 'Note deleted successfully');
    }
}

laravel/resources/views/notes/create.blade.php
@extends('layouts.app')
@include('includes.header')
@section('content')
   <div class="container">
       <div class="row">
           <div class="col-lg-12 margin-tb">
               <div class="pull-left">
                   <h2>Add New Note</h2>
               </div>
               <div class="pull-right">
                   <a class="btn btn-primary" href="{{ route('notes.index') }}"> Back</a>
               </div>
           </div>
       </div>

       @if ($errors->any())
           <div class="alert alert-danger">
               <strong>Whoops!</strong> There were some problems with your input.<br><br>
               <ul>
                   @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                   @endforeach
               </ul>
           </div>
       @endif

       <form action="{{ route('notes.store') }}" method="POST">
           @csrf

           <div class="row">
               <div class="col-xs-12 col-sm-12 col-md-12">
                   <div class="form-group">
                       <strong>Title:</strong>
                       <input type="hidden" name="user_id" value="{{\Illuminate\Support\Facades\Auth::user()->id}}">
                       <input type="text" name="title" class="form-control" placeholder="Title">
                   </div>
               </div>
               <div class="col-xs-12 col-sm-12 col-md-12">
                   <div class="form-group">
                       <strong>Note:</strong>
                       <textarea class="form-control" style="height:150px" name="note" placeholder="note"></textarea>
                   </div>
               </div>
               <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                   <button type="submit" class="btn btn-primary">Submit</button>
               </div>
           </div>

       </form>
   </div>
@endsection

laravel/resources/views/notes/edit.blade.php
@extends('layouts.app')
@include('includes.header')
@section('content')
   <div class="container">
       <div class="row">
           <div class="col-lg-12 margin-tb">
               <div class="pull-left">
                   <h2>Edit Note</h2>
               </div>
               <div class="pull-right">
                   <a class="btn btn-primary" href="{{ route('notes.index') }}"> Back</a>
               </div>
           </div>
       </div>

       @if ($errors->any())
           <div class="alert alert-danger">
               <strong>Whoops!</strong> There were some problems with your input.<br><br>
               <ul>
                   @foreach ($errors->all() as $error)
                       <li>{{ $error }}</li>
                   @endforeach
               </ul>
           </div>
       @endif

       <form action="{{ route('notes.update',$note->id) }}" method="POST">
           @csrf
           @method('PUT')

           <div class="row">
               <div class="col-xs-12 col-sm-12 col-md-12">
                   <div class="form-group">
                       <strong>Title:</strong>
                       <input type="text" name="title" value="{{ $note->title }}" class="form-control" placeholder="Title">
                   </div>
               </div>
               <div class="col-xs-12 col-sm-12 col-md-12">
                   <div class="form-group">
                       <strong>Note:</strong>
                       <textarea class="form-control" style="height:150px" name="note" placeholder="Note">{{ $note->note }}</textarea>
                   </div>
               </div>
               <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                   <button type="submit" class="btn btn-primary">Submit</button>
               </div>
           </div>

       </form>
   </div>
@endsection

laravel/resources/views/notes/index.blade.php
@extends('layouts.app')
@include('includes.header')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2>Note</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-success float-right" href="{{ route('notes.create') }}"> Create New Note</a>
                </div>
            </div>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Details</th>
                <th width="280px">Action</th>
            </tr>
            @foreach ($notes as $note)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $note->title }}</td>
                    <td>{{ $note->note }}</td>
                    <td>
                        <form action="{{ route('notes.destroy',$note->id) }}" method="POST">

                            <a class="btn btn-info" href="{{ route('notes.show',$note->id) }}">Show</a>

                            <a class="btn btn-primary" href="{{ route('notes.edit',$note->id) }}">Edit</a>

                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>

        {!! $notes->links() !!}
    </div>


@endsection

laravel/resources/views/notes/show.blade.php
@extends('layouts.app')
@include('includes.header')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-12 margin-tb">
                <div class="pull-left">
                    <h2> Show Note</h2>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{ route('notes.index') }}"> Back</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    {{ $note->title }}
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Note:</strong>
                    {{ $note->note }}
                </div>
            </div>
        </div>
    </div>

@endsection